[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate 2>&1; echo 'Starting gunicorn...'; gunicorn src.asgi:application --workers 1 -k uvicorn.workers.UvicornWorker --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT --timeout 200 --log-level debug --capture-output --error-logfile - --access-logfile - 2>&1; echo \"Gunicorn exited with code: $?\""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10


